#!/bin/sh
### push /dist folder on gh-pages branch ! ( served via gh-pages)
git add .
git commit -m ','

git push origin main
yarn build

git commit -am "Save uncommited changes (WIP)"
git branch --delete --force gh-pages
git checkout --orphan gh-pages
echo "ubi.hiddenlabs.cc" > dist/CNAME
git add -f dist
git commit -m "Rebuild GitHub pages"
git filter-branch -f --prune-empty --subdirectory-filter dist && git push -f origin gh-pages && git checkout -
git checkout main
