#!/bin/sh
### push /dist folder on gh-pages branch ! ( served via gh-pages)
git add .
git commit -m ','

git push origin main
yarn build
echo '<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>404 Not Found</title>
  <script>
    function redirectToHome() {
      window.history.replaceState({}, document.title, window.location.pathname);
      window.location.href = "/";
    }
  </script>
</head>
<body onload="redirectToHome()">
</body>
</html>' > 404.html
git commit -am "Save uncommited changes (WIP)"
git branch --delete --force gh-pages
git checkout --orphan gh-pages
echo "ubi.hiddenlabs.cc" > dist/CNAME
git add -f dist
git commit -m "Rebuild GitHub pages"
git filter-branch -f --prune-empty --subdirectory-filter dist && git push -f origin gh-pages && git checkout -
git checkout main
