name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Déploie lorsque la branche main est mise à jour

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ajustez selon votre projet
          cache: 'yarn'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: yarn install

      # Étape 4 : Construire le projet
      - name: Build project
        run: yarn build

      # Étape 5 : Déployer sur la branche gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Chemin du dossier généré après le build
